# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: quay.io/pik-software/base:v1.10

      - image: mdillon/postgis:9.6
        environment:
          POSTGRES_DB: repo
          POSTGRES_USER: postgres

      - image: redis:3.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            set +x
            pip install -e '.[dev]'

      - run:
          name: run tests
          command: |
            . .venv/bin/activate
            set +x
            python setup.py check -m -s
            pytest --doctest-modules --durations=0 -vvv tests
            prospector --profile-path . --profile .prospector.yaml .
            pip check
